from datetime import datetime
from typing import TYPE_CHECKING, Any
from uuid import UUID

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.domain.message_status import MessageWorkflowStatus
from src.models.base import Base

if TYPE_CHECKING:
    from src.models.group import Group
    from src.models.member import Member
    from src.models.requests import Requests


class Message(Base):
    __tablename__ = "messages"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    group_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("groups.id"),
        nullable=False,
        index=True,
    )
    # The member this row is *about*: the sender on inbound, the recipient on
    # outbound. Not necessarily whoever wrote it.
    member_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("members.id"),
        nullable=True,
        index=True,
    )
    # Who wrote it. NULL exactly when nobody did: a fan-out copy is generated by
    # the system from a body someone else already wrote.
    author_member_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("members.id"),
        nullable=True,
    )
    # Parentage, and nothing more. Every message in a thread carries it,
    # including the original, so it cannot tell you what a message *is*.
    request_id: Mapped[int | None] = mapped_column(
        BigInteger,
        ForeignKey("requests.id", name="messages_request_id_fkey"),
        nullable=True,
        index=True,
    )
    # Message-graph edge, not a Conversation entity.
    # For fan-out copies and replies: points at the *original routed inbound*
    # (star topology). Do not retarget to the immediately preceding SMS.
    # A future Conversation/Thread may group these; parent_message_id alone
    # is not the full definition of a conversation.
    parent_message_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("messages.id"),
        nullable=True,
        index=True,
    )
    direction: Mapped[str] = mapped_column(String(20), nullable=False)
    from_phone_number: Mapped[str] = mapped_column(String(16), nullable=False)
    to_phone_number: Mapped[str] = mapped_column(String(16), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    provider_message_id: Mapped[str | None] = mapped_column(String(64), unique=True)

    workflow_status: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        server_default=text(f"'{MessageWorkflowStatus.RECEIVED.value}'"),
    )
    # Who is speaking: member, moderator, or the system itself.
    sender_role: Mapped[str | None] = mapped_column(String(16))
    # What this message is. Stamped once by whichever path creates the row, and
    # never re-derived from request_id, parent_message_id, direction or timing.
    kind: Mapped[str | None] = mapped_column(String(32))
    # Snapshot of the group policy in force when this request was handled, so
    # later policy changes cannot rewrite history. NULL for replies/outbound.
    routing_policy: Mapped[str | None] = mapped_column(String(32))
    intent: Mapped[str | None] = mapped_column(String(64))
    constraints: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    confidence: Mapped[float | None] = mapped_column(Float)
    suggested_recipient_ids: Mapped[list[UUID] | None] = mapped_column(
        ARRAY(PG_UUID(as_uuid=True))
    )
    # Who this was routed to — true whether a moderator approved or a policy
    # authorized it. Pair with workflow_status to tell which happened.
    routed_recipient_ids: Mapped[list[UUID] | None] = mapped_column(
        ARRAY(PG_UUID(as_uuid=True))
    )
    processing_notes: Mapped[str | None] = mapped_column(Text)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    group: Mapped["Group"] = relationship(back_populates="messages")
    member: Mapped["Member | None"] = relationship(
        back_populates="messages",
        foreign_keys=[member_id],
    )
    author: Mapped["Member | None"] = relationship(foreign_keys=[author_member_id])
    request: Mapped["Requests | None"] = relationship(
        foreign_keys=[request_id],
        back_populates="messages",
    )
    parent: Mapped["Message | None"] = relationship(
        remote_side=[id],
        foreign_keys=[parent_message_id],
    )

    __table_args__ = (
        CheckConstraint(
            "direction IN ('inbound', 'outbound')",
            name="messages_direction_check",
        ),
        CheckConstraint(
            "workflow_status IN ("
            "'received', 'processing', 'awaiting_moderator', 'approved', "
            "'auto_authorized', 'delivering', 'sent', 'delivered', "
            "'partially_delivered', 'processing_failed', 'moderator_rejected', "
            "'delivery_failed')",
            name="messages_workflow_status_check",
        ),
        CheckConstraint(
            "sender_role IS NULL OR sender_role IN "
            "('member', 'moderator', 'system')",
            name="messages_sender_role_check",
        ),
        CheckConstraint(
            "kind IS NULL OR kind IN ("
            "'original_request', 'moderator_clarification', 'member_reply', "
            "'fanout_copy', 'confirmation')",
            name="messages_kind_check",
        ),
        # The five legal row shapes, enforced structurally because several code
        # paths create messages and a wrong pairing corrupts a thread's meaning.
        CheckConstraint(
            "kind IS NULL"
            " OR (kind IN ('original_request', 'member_reply', 'confirmation')"
            "     AND sender_role = 'member'"
            "     AND author_member_id IS NOT NULL"
            "     AND author_member_id = member_id)"
            " OR (kind = 'moderator_clarification'"
            "     AND sender_role = 'moderator'"
            "     AND author_member_id IS NOT NULL)"
            " OR (kind = 'fanout_copy'"
            "     AND sender_role = 'system'"
            "     AND author_member_id IS NULL)",
            name="messages_role_shape_check",
        ),
        CheckConstraint(
            "routing_policy IS NULL OR routing_policy IN "
            "('moderator_required', 'auto_group', 'auto_matched')",
            name="messages_routing_policy_check",
        ),
    )
