CREATE TABLE public.messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,

    group_id uuid NOT NULL
        REFERENCES public.groups(id),

    -- The member this row is *about*: the sender on inbound, the recipient on
    -- outbound. Not necessarily the person who wrote it -- see author_member_id.
    member_id uuid NULL
        REFERENCES public.members(id),

    -- Who wrote this message. NULL exactly when nobody did (fan-out copies are
    -- generated by the system from an existing body).
    author_member_id uuid NULL
        REFERENCES public.members(id),

    -- Parentage only. Every message in a thread carries it, including the
    -- original, so it says nothing about what a message *is*: read kind.
    request_id bigint NULL
        REFERENCES public.requests(id),

    -- Link replies / fan-out copies back to the originating inbound message
    parent_message_id uuid NULL
        REFERENCES public.messages(id),

    direction varchar(20) NOT NULL,

    from_phone_number varchar(16) NOT NULL,
    to_phone_number varchar(16) NOT NULL,

    body text NOT NULL,

    provider_message_id varchar(64) NULL,

    -- Explicit workflow lifecycle for inbound routing messages
    workflow_status varchar(32) NOT NULL DEFAULT 'received',

    -- Who is speaking: member, moderator, or the system itself.
    sender_role varchar(16) NULL,

    -- What this message is, stamped once by whichever path creates the row and
    -- never re-derived from request_id, parent_message_id, direction or timing.
    kind varchar(32) NULL,

    -- Group routing policy in force when this request was handled. NULL for
    -- replies and outbound copies. Snapshot: changing the group's policy later
    -- must not rewrite history.
    routing_policy varchar(32) NULL,

    intent varchar(64) NULL,
    constraints jsonb NULL,
    confidence double precision NULL,
    suggested_recipient_ids uuid[] NULL,
    -- Who the message was routed to, whether a moderator approved or a group
    -- policy authorized it.
    routed_recipient_ids uuid[] NULL,
    processing_notes text NULL,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT messages_direction_check
        CHECK (direction IN ('inbound', 'outbound')),

    CONSTRAINT messages_workflow_status_check
        CHECK (workflow_status IN (
            'received',
            'processing',
            'awaiting_moderator',
            'approved',
            'auto_authorized',
            'delivering',
            'sent',
            'delivered',
            'partially_delivered',
            'processing_failed',
            'moderator_rejected',
            'delivery_failed'
        )),

    CONSTRAINT messages_sender_role_check
        CHECK (sender_role IS NULL OR sender_role IN (
            'member',
            'moderator',
            'system'
        )),

    CONSTRAINT messages_kind_check
        CHECK (kind IS NULL OR kind IN (
            'original_request',
            'moderator_clarification',
            'member_reply',
            'fanout_copy',
            'confirmation'
        )),

    -- The five legal row shapes. Structural rather than conventional, because
    -- several code paths create messages and a wrong pairing here would quietly
    -- corrupt the meaning of a thread.
    CONSTRAINT messages_role_shape_check
        CHECK (
            kind IS NULL
            OR (
                kind IN ('original_request', 'member_reply', 'confirmation')
                AND sender_role = 'member'
                AND author_member_id IS NOT NULL
                AND author_member_id = member_id
            )
            OR (
                kind = 'moderator_clarification'
                AND sender_role = 'moderator'
                AND author_member_id IS NOT NULL
            )
            OR (
                kind = 'fanout_copy'
                AND sender_role = 'system'
                AND author_member_id IS NULL
            )
        ),

    CONSTRAINT messages_routing_policy_check
        CHECK (routing_policy IS NULL OR routing_policy IN (
            'moderator_required',
            'auto_group',
            'auto_matched'
        )),

    CONSTRAINT messages_provider_message_id_unique
        UNIQUE (provider_message_id)
);

CREATE INDEX idx_messages_group_id
    ON public.messages(group_id);

CREATE INDEX idx_messages_member_id
    ON public.messages(member_id);

CREATE INDEX idx_messages_request_id
    ON public.messages(request_id);

CREATE INDEX idx_messages_group_created
    ON public.messages(group_id, created_at DESC);

CREATE INDEX idx_messages_workflow_status
    ON public.messages(workflow_status);

CREATE INDEX idx_messages_parent_message_id
    ON public.messages(parent_message_id);

-- "Which open requests reached this member?" -- the fan-out copy records its
-- recipient in member_id, so participation is a column lookup.
CREATE INDEX idx_messages_fanout_recipient
    ON public.messages(member_id, created_at DESC)
    WHERE kind = 'fanout_copy';

ALTER TABLE public.requests
    ADD CONSTRAINT requests_original_message_id_fkey
    FOREIGN KEY (original_message_id)
    REFERENCES public.messages(id);
